name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0" # Specify the Flutter version you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Analyze the project source
      - name: Analyze project source
        run: flutter analyze

      # Step 5: Run tests
      - name: Run Flutter tests
        run: flutter test

      # Optional: Verify formatting (uncomment if needed)
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .
