name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the project code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0" # You can specify the Flutter version

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Analyze the Flutter project source
      - name: Analyze project source
        run: flutter analyze

      # Step 5: Run Flutter tests
      - name: Run Flutter tests
        run: flutter test

      # Optional: Verify code formatting
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .
